#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Semantic version regex (https://semver.org/)
 * Matches: 0.0.1, 1.2.3, 1.0.0-beta.1, 2.0.0+build.123, etc.
 */
const SEMVER_REGEX = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/;

/**
 * Read and validate package.json version
 */
function readPackageVersion() {
  const packageJsonPath = join(__dirname, '..', 'package.json');

  try {
    const content = readFileSync(packageJsonPath, 'utf-8');
    const pkg = JSON.parse(content);

    if (!pkg.version) {
      console.error('❌ Error: No version field found in package.json');
      process.exit(1);
    }

    if (!SEMVER_REGEX.test(pkg.version)) {
      console.error(`❌ Error: Invalid semantic version "${pkg.version}" in package.json`);
      console.error('   Expected format: MAJOR.MINOR.PATCH (e.g., 1.2.3, 1.0.0-beta.1)');
      process.exit(1);
    }

    return pkg.version;
  } catch (error) {
    if (error.code === 'ENOENT') {
      console.error('❌ Error: package.json not found at', packageJsonPath);
    } else if (error instanceof SyntaxError) {
      console.error('❌ Error: Invalid JSON in package.json');
    } else {
      console.error('❌ Error reading package.json:', error.message);
    }
    process.exit(1);
  }
}

/**
 * Generate src/version.ts with current version
 */
function generateVersionFile(version) {
  const versionFilePath = join(__dirname, '..', 'src', 'version.ts');

  try {
    // Check if file exists and read current version
    let currentVersion = null;
    try {
      const existingContent = readFileSync(versionFilePath, 'utf-8');
      const match = existingContent.match(/VERSION = ['"]([^'"]+)['"]/);
      if (match) {
        currentVersion = match[1];
      }
    } catch {
      // File doesn't exist yet, that's fine
    }

    if (currentVersion === version) {
      console.log(`✓ Version file already up to date: ${version}`);
      return false;
    }

    // Generate new version file
    const content = `// Auto-generated by scripts/inject-version.js
// DO NOT EDIT MANUALLY - This file is generated during build

/**
 * Current package version from package.json
 * Automatically synchronized during build process
 */
export const VERSION = '${version}';
`;

    writeFileSync(versionFilePath, content, 'utf-8');

    if (currentVersion) {
      console.log(`✓ Version file updated: ${currentVersion} → ${version}`);
    } else {
      console.log(`✓ Version file created: ${version}`);
    }
    return true;
  } catch (error) {
    console.error('❌ Error generating version file:', error.message);
    process.exit(1);
  }
}

// Main execution
try {
  const version = readPackageVersion();
  const updated = generateVersionFile(version);

  if (!updated) {
    console.log(`\n✅ Version is synchronized: ${version}`);
  } else {
    console.log(`\n✅ Version synchronization complete: ${version}`);
  }
} catch (error) {
  console.error('❌ Unexpected error:', error.message);
  process.exit(1);
}
