export type {
  AnimationMetadata,
  VideoMetadata,
  FrameMetadata,
  FrameChange,
  ToolMetadata,
  ToolParams,
  SheetMetadata,
  SheetOptions,
  SieveMetadata,
  EdgeMetadata,
  EdgeChange,
  BoundingBox,
  DBSCANResult,
  FrameNode,
  ProcessContext,
  ProgressPhase,
  ResolvedOptions,
  ScoreEdge,
  SieveInput,
  SieveOptions,
  SieveOptionsBase,
  SieveResult,
} from './types/index.js';

export { runPipeline as extractScenes } from './core/index.js';
